### ISSUE TITLE
Needs Example when switching to "Webhook Mode"

### ISSUE THREAD

**Issue by Ev1dentFir3** [leovoel/embed-visualizer#14]
When we enable Webhook Mode can you update the example embed to a valid form please so we can see what it's supposed to look like, Thanks.

**Comment by leovoel** [comment]
sure, although i'll have to add a warning to it saying it will clear your input.

**Comment by Evident-Dev** [comment]
Thanks 👍

**Comment by Evident-Dev** [comment]
Thanks 👍
