### ISSUE TITLE
Color Codes - What kind?

### ISSUE THREAD

**Issue by ethamitc** [leovoel/embed-visualizer#27]
I'm trying to set custom colors for the embed, however I have no clue what kind of color code that is. Could you please provide the name of the type of color code that should be used.

**Comment by ghost** [comment]
+1... Very confusing.

**Comment by ethamitc** [comment]
@gxrneyme I just realized that there is a color picker button on the bottom, It would be nice to be able to use custom color codes, however not everything nice to you in programming...

**Comment by ghost** [comment]
I worked it out... put your hex code into the "enter hex number" field at https://www.rapidtables.com/convert/number/hex-to-decimal.html, and the result in the "decimal number" field is the colour code.

**Comment by ethamitc** [comment]
@gxrneyme Thanks mate!
